name: environment_supervisedMLspiral
channels:
  - defaults
dependencies:
  - imbalanced-learn=0.11.0
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - numpy=1.23.5
  - numpy-base=1.23.5
  - pandas=2.1.1
  - pip=23.3.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python-tzdata=2023.3
  - scikit-learn=1.3.0
  - seaborn=0.13.2
  - termcolor=2.1.0
  - notebook=7.0.6
